"use strict";
exports.__esModule = true;
var proffesional_1 = require("./proffesional");
var movie_1 = require("./movie");
var imdb_1 = require("./imdb");
var pelicula1 = new movie_1.Movie("Harry Potter", 2001, "Britanica", "Aventura");
var actor1 = new proffesional_1.Proffesional("Alan Rickman", 69, "masculino", 84, 185, "gris", "café", "blanco", true, "Reino Unido", 0, "actor");
var actor2 = new proffesional_1.Proffesional("Helena Bonham Carter", 55, "femenino", 59, 157, "castaño", "negro", "blanco", false, "Reino Unido", 0, "actriz");
var actores = [actor1, actor2];
var director1 = new proffesional_1.Proffesional("David Yates", 58, "masculino", 80, 180, "rubio", "azul", "blanco", false, "Reino Unido", 0, "director");
var escritor1 = new proffesional_1.Proffesional("J.k. Rowling", 56, "femenino", 65, 170, "rubio", "azul", "blanco", false, "Reino Unido", 0, "escritora");
pelicula1.setActors(actores);
pelicula1.setDirector(director1);
pelicula1.setWriter(escritor1);
pelicula1.setLanguage("inglés");
pelicula1.setPlataform("HBO");
pelicula1.setIsMCU(false);
pelicula1.setMainCharacterName("Harry Potter");
pelicula1.setProducer("Warner Bros");
pelicula1.setDistributor("Warner Bros");
var pelicula2 = new movie_1.Movie("Pretty Woman", 1990, "americana", "comedia romantica");
var actor3 = new proffesional_1.Proffesional("Julia Roberts", 54, "femenino", 60, 175, "castaño", "marron", "blanco", false, "USA", 1, "actriz");
var actor4 = new proffesional_1.Proffesional("Richard Gere", 72, "masculino", 80, 180, "gris", "negro", "blanco", false, "USA", 0, "actor");
var actores2 = [actor3, actor4];
var director2 = new proffesional_1.Proffesional("Garry Marshall", 81, "masculino", 75, 179, "gris", "azul", "blanco", true, "USA", 0, "director");
var escritor2 = new proffesional_1.Proffesional("J. F. Lawton", 61, "masculino", 85, 174, "castaño", "marron", "blanco", false, "USA", 0, "guionista");
pelicula2.setActors(actores2);
pelicula2.setDirector(director2);
pelicula2.setWriter(escritor2);
pelicula2.setLanguage("inglés");
pelicula2.setPlataform("Disney+");
pelicula2.setIsMCU(false);
pelicula2.setMainCharacterName("Vivian Ward");
pelicula2.setProducer("Toucstone Pictures");
pelicula2.setDistributor("Walt Disney Studios");
var peliculas = [pelicula1, pelicula2];
var prueba = new imdb_1.Imdb(peliculas);
console.log(prueba);
