"use strict";
exports.__esModule = true;
var proffesional_1 = require("./proffesional");
var movie_1 = require("./movie");
var pelicula1 = new movie_1.Movie("Harry Potter", 2001, "Britanica", "Aventura");
var actor1 = new proffesional_1.Proffesional("Alan Rickman", 69, "masculino", 84, 185, "gris", "café", "blanco", true, "Reino Unido", 0, "actor");
var actor2 = new proffesional_1.Proffesional("Helena Bonham Carter", 55, "femenino", 59, 157, "castaño", "negro", "blanco", false, "Reino Unido", 0, "actriz");
var actores = [actor1, actor2];
var director1 = new proffesional_1.Proffesional("David Yates", 58, "masculino", 80, 180, "rubio", "azul", "blanco", false, "Reino Unido", 0, "director");
var escritor1 = new proffesional_1.Proffesional("J.k. Rowling", 56, "femenino", 65, 170, "rubio", "azul", "blanco", false, "Reino Unido", 0, "escritora");
pelicula1.setActors(actores);
pelicula1.setDirector(director1);
pelicula1.setWriter(escritor1);
pelicula1.setLanguage("inglés");
pelicula1.setPlataform("HBO");
pelicula1.setIsMCU(false);
pelicula1.setMainCharacterName("Harry Potter");
pelicula1.setProducer("Warner Bros");
pelicula1.setDistributor("Warner Bros");
pelicula1.printMovie();
